[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Alina T <alina1989malina@yandex.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

pcsc = "2.4.0"